### ISSUE TITLE
data is possibly null

### ISSUE THREAD

**Issue by danialdezfouli** [bdsqqq/try#4]
after handling the error and we are sure that the data is not null anymore, typescript cannot detect this and considers the data nullable. ts is still thinking about [null, error]

I was curious if it could be fixed though it is a typescript limit

```ts
const fetchData = () => Promise.resolve({id: 1})
const [data, error] = await trytm(fetchData())
if (error) {
  return
}

data.id // data is possibly null 
```

**Comment by danialdezfouli** [comment]
maybe by changing this line with adding a bang

```ts
return [null!, error] as const
```

**Comment by bdsqqq** [comment]
> maybe by changing this line with adding a bang
> 
> ```ts
> return [null!, error] as const
> ```

Tried it but the behavior is still the same. 
I'll focus on other projects for now but might revisit this at some point. Feel free to open a PR if you find a solution.

**Comment by adwinying** [comment]
Since anything can be thrown, it's probably a good idea to check whether error is actually an instance of `Error`.
Frameworks like [Remix](https://remix.run/docs/en/v1/route/loader#throwing-responses-in-loaders) allows for throwing of responses and this could avoid breaking such functionality.
