### ISSUE TITLE
Package types are wrong

### ISSUE THREAD

**Issue by AlexisWalravens** [bdsqqq/try#9]
Hi, first thanks for making this!

I just tried it but it seems the types that are transpiled in the packags look like this:
```ts
declare const trytm: <T>(
   promise: Promise<T>,
) => Promise<readonly [Awaited<T>, null] | readonly [null, unknown]>;

export { trytm };
```

And the part that breaks is the `| readonly [null, unknown]>`

Because now if I try to use the package
```ts
const [data, error] = await trytm(myPromise())
```

`error` is `unknown` so even if I check if `error !== null` afterwards, the data type is not narrowed to not be `null`.

When copy/pasting the source in a helper directly in project it works alright.

**Comment by bdsqqq** [comment]
Thanks for opening this issue, just fixed it in v2.3.0. 
Let me know if the error persists after upgrading
